"""Git configuration management service: includes, profiles, safe atomic backups, and inspection."""
from datetime import datetime
import logging
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
from typing import Any, Dict, List, Optional

from github_account_manager.config import BACKUP_DIR, DEFAULT_GITCONFIG
from github_account_manager.models import Account, FolderMapping, sanitize_git_string

logger = logging.getLogger(__name__)


class GitService:
    def __init__(self, gitconfig_path: Optional[Path] = None, home_dir: Optional[Path] = None):
        self.gitconfig_path = gitconfig_path or DEFAULT_GITCONFIG
        self.home_dir = home_dir or Path.home()

    def create_backup(self) -> Optional[Path]:
        """Create a timestamped backup of the current global .gitconfig and prune old backups."""
        if not self.gitconfig_path.exists():
            return None
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_file = BACKUP_DIR / f"gitconfig_{timestamp}.bak"
        try:
            shutil.copy2(self.gitconfig_path, backup_file)
            self._prune_backups(keep=15)
            return backup_file
        except Exception as e:
            logger.error(f"Failed to create gitconfig backup: {e}")
            return None

    def _prune_backups(self, keep: int = 15) -> None:
        """Keep only the latest N backups."""
        try:
            backups = sorted(list(BACKUP_DIR.glob("*.bak")), key=lambda p: p.stat().st_mtime, reverse=True)
            for old_bak in backups[keep:]:
                old_bak.unlink()
        except Exception as e:
            logger.debug(f"Backup pruning error: {e}")

    def write_account_profile_config(self, account: Account) -> Path:
        """
        Generate and write ~/.gitconfig-<slug> for a specific account using atomic replacement.
        """
        profile_path = self.home_dir / account.config_filename

        clean_name = sanitize_git_string(account.git_name)
        clean_email = sanitize_git_string(account.email)

        content_lines = [
            f"# Generated by GitHub Multi-Account Manager for profile: {account.name}",
            "[user]",
            f"\tname = {clean_name}",
            f"\temail = {clean_email}",
        ]

        if account.ssh_key_path:
            clean_ssh = sanitize_git_string(account.ssh_key_path)
            ssh_posix = Path(clean_ssh).as_posix()
            content_lines.extend([
                "[core]",
                f"\tsshCommand = ssh -i {ssh_posix} -o IdentitiesOnly=yes",
            ])

        content_lines.append("")
        self._atomic_write(profile_path, "\n".join(content_lines))
        return profile_path

    def remove_account_profile_config(self, account: Account) -> None:
        """Remove the ~/.gitconfig-<slug> file."""
        profile_path = self.home_dir / account.config_filename
        if profile_path.exists():
            try:
                profile_path.unlink()
            except Exception as e:
                logger.error(f"Failed to delete {profile_path}: {e}")

    def sync_global_gitconfig(
        self,
        accounts: List[Account],
        mappings: List[FolderMapping],
    ) -> bool:
        """
        Safely update ~/.gitconfig with includeIf sections corresponding to folder mappings.
        Preserves all other sections and comments in the existing gitconfig.
        """
        self.create_backup()

        account_map = {acc.id: acc for acc in accounts}

        # Write each account profile file first
        for acc in accounts:
            self.write_account_profile_config(acc)

        existing_text = ""
        if self.gitconfig_path.exists():
            try:
                existing_text = self.gitconfig_path.read_text(encoding="utf-8-sig")
            except Exception:
                pass

        # Strip out previously managed includeIf blocks
        lines = existing_text.splitlines()
        filtered_lines = []

        i = 0
        while i < len(lines):
            line = lines[i]
            # Check if this is an includeIf header
            if re.match(r'^\s*\[includeIf\s+["\'].*["\']\]', line, re.IGNORECASE):
                # Check following lines to see if path points to a managed ~/.gitconfig-*
                j = i + 1
                is_managed = False
                while j < len(lines) and not lines[j].strip().startswith("["):
                    if re.search(r'path\s*=\s*~?/?\.gitconfig-', lines[j], re.IGNORECASE):
                        is_managed = True
                    j += 1

                if is_managed:
                    i = j
                    continue
                else:
                    filtered_lines.append(line)
                    i += 1
            else:
                filtered_lines.append(line)
                i += 1

        clean_text = "\n".join(filtered_lines).rstrip()

        # Build new includeIf blocks
        include_blocks = []
        for mapping in mappings:
            acc = account_map.get(mapping.account_id)
            if not acc:
                continue

            normalized_folder = mapping.normalized_path
            include_blocks.append(
                f'[includeIf "gitdir/i:{normalized_folder}"]\n\tpath = ~/{acc.config_filename}'
            )

        if include_blocks:
            new_content = clean_text + "\n\n" + "\n\n".join(include_blocks) + "\n"
        else:
            new_content = clean_text + "\n" if clean_text else ""

        self._atomic_write(self.gitconfig_path, new_content)
        self.sync_ssh_config(accounts)
        return True

    def sync_ssh_config(self, accounts: List[Account]) -> Path:
        """
        Generate ~/.ssh/config with per-account host aliases and port 443 fallback.
        This provides bulletproof identity isolation for external IDEs like VS Code and Cursor.
        """
        ssh_dir = self.home_dir / ".ssh"
        ssh_dir.mkdir(parents=True, exist_ok=True)
        ssh_config_path = ssh_dir / "config"

        lines = [
            "# Generated by GitHub Multi-Account Manager",
            "# Configured with port 443 (ssh.github.com) for firewall & ISP reliability",
            "",
            "Host github.com",
            "    HostName ssh.github.com",
            "    Port 443",
            "    User git",
            "",
        ]

        for acc in accounts:
            if acc.ssh_key_path:
                key_posix = Path(acc.ssh_key_path).as_posix()
                slug = acc.name.lower().replace(" ", "-").replace("_", "-")
                lines.extend([
                    f"# Account Profile: {acc.name} ({acc.email})",
                    f"Host github-{slug}",
                    "    HostName ssh.github.com",
                    "    Port 443",
                    "    User git",
                    f"    IdentityFile {key_posix}",
                    "    IdentitiesOnly yes",
                    "",
                ])

        self._atomic_write(ssh_config_path, "\n".join(lines))
        return ssh_config_path

    def inspect_directory(self, target_path: Path | str) -> Dict[str, Any]:
        """
        Inspect a folder or repository to find out what Git identity & SSH command applies.
        """
        p = Path(target_path)
        if not p.exists():
            return {
                "exists": False,
                "is_git_repo": False,
                "error": f"Path '{p}' does not exist.",
            }

        is_repo = (p / ".git").exists() or (p / "HEAD").exists()

        result = {
            "path": str(p),
            "normalized_path": p.as_posix(),
            "exists": True,
            "is_git_repo": is_repo,
            "user_name": "",
            "user_email": "",
            "ssh_command": "",
        }

        try:
            cmd_name = subprocess.run(
                ["git", "-C", str(p), "config", "user.name"],
                capture_output=True,
                text=True,
                check=False,
                timeout=5,
            )
            result["user_name"] = cmd_name.stdout.strip()

            cmd_email = subprocess.run(
                ["git", "-C", str(p), "config", "user.email"],
                capture_output=True,
                text=True,
                check=False,
                timeout=5,
            )
            result["user_email"] = cmd_email.stdout.strip()

            cmd_ssh = subprocess.run(
                ["git", "-C", str(p), "config", "core.sshCommand"],
                capture_output=True,
                text=True,
                check=False,
                timeout=5,
            )
            result["ssh_command"] = cmd_ssh.stdout.strip()

        except Exception as e:
            result["error"] = str(e)

        return result

    def get_gitconfig_content(self) -> str:
        """Return the raw text of ~/.gitconfig."""
        if self.gitconfig_path.exists():
            try:
                return self.gitconfig_path.read_text(encoding="utf-8")
            except Exception:
                return ""
        return ""

    def _atomic_write(self, target: Path, content: str) -> None:
        """Write to a temporary file in the same directory and replace atomically."""
        target.parent.mkdir(parents=True, exist_ok=True)
        tmp_file = target.parent / f"{target.name}.tmp_{datetime.now().strftime('%Y%m%d%H%M%S%f')}"
        try:
            tmp_file.write_text(content, encoding="utf-8")
            tmp_file.replace(target)
        except Exception as e:
            if tmp_file.exists():
                try:
                    tmp_file.unlink()
                except Exception:
                    pass
            raise e